### PR TITLE
NDattributes - add/update fine positioner PVs

### LINKED ISSUE #40: add fine positioner readback PVs to NDattributes
https://github.com/BCDA-APS/bdp_controls/blob/4d03dc272e584dabe8d5b079f4335cbe59d7ea31/qserver/instrument/plans/trajectories.py#L156

### PR DESCRIPTION
**Pull request by prjemian**
- Close #40

### CODE REVIEW

**Review by prjemian — COMMENTED** [review]
looks OK

**Comment by sveseli** [comment]
Was this really Roger's commit?

**Comment by prjemian** [comment]
Roger is very talented!  No. But somewhere in the account on terrier, his name is associated with the `git commit` command. I did this commit, et al.

**Comment by sveseli** [comment]
I suppose git can be configured to set author/email for commits. :-)

**Pull request merged**
