### PR TITLE
bluesky instrument package 

### LINKED ISSUE #4: create bluesky instrument package for BDP controls
Start with template [instrument](https://github.com/BCDA-APS/bluesky_training/tree/main/bluesky/instrument) from APS bluesky training repository.

Need support for:

- shutter
- simulated beam intensity
  - include shutter in simulator
- ADSimDetector
  - simulated peak mode
  - randomized position and live jitter
  - include simulated beam intensity in simulator
- couple motors
- couple piezos (simulate with floating-point `ao` PVs)

## Addition

Not really part of bluesky, but shows local pipeline.

- ADSimDetector sends PVA output to AD's pvaPlugin IOC

### PR DESCRIPTION
**Pull request by prjemian**
- Close #4
- Reference #9

### CODE REVIEW

**Review by tguruswamy — APPROVED** [review]
Is there functionality to pretend to start to take a long exposure image, and then abort? Do we need something like that?

**Comment by prjemian** [comment]
*Abort the scan* is a feature of the RunEngine, either ^C^C in interactive session or queueserver command (see #10).

Configuration of acquisition time is provided as standard support.  We need to make sure we provide this feature in `instrument/plans`.

I believe that is part of the basic feedback process: we need it.

**Comment by prjemian** [comment]
>  We need to make sure we provide this feature in instrument/plans.

See #11

**Comment by prjemian** [comment]
Thanks!

**Pull request merged**
