### PR TITLE
create & use attributes.xml file

### LINKED ISSUE #21: Configure adsimdet to bundle metadata into the PVA image pv
Write an `attributes.xml` file and load it into the `adsimdet` object.

### PR DESCRIPTION
**Pull request by prjemian**
- Fix #21

### CODE REVIEW

**Review by tguruswamy — APPROVED** [review]
Does areaDetector give a warning/error if any of the attributes cannot be read, e.g. typo in the PV name?

**Comment by prjemian** [comment]
AD only gives a boolean on the entire file, acceptable or not. No coaching
on what might be an error.  There is an XML Schema available to use with
xmllint.

**Comment by MarkRivers** [comment]
The boolean for the entire file is for XML syntax errors, not whether the PV is actually reachable.  It is not an error for a PV to not be reachable, because the IOC hosting it may be down at the time the AD IOC is started, but it may become reachable later.  It is thus not possible to detect typos in PV names.

**Comment by prjemian** [comment]
@MarkRivers Thanks!

**Pull request merged**
